[feature/#18] 지도 검색 구현
TeamFILL-IN/Fill-Android pull request #23
Opened 2022-01-12 15:34 UTC by kkk5474096

## Related Issues
close#18

## What Did You Do?
- [ ] 검색 창
- [ ] 검색 취소
- [ ] 지도 정보 리사이클러뷰 구현

2022-01-12 16:13 UTC, hyunji24 approved these changes
LZTM MVP👍

2022-01-12 16:18 UTC, l2hyunwoo requested changes
레이아웃은 일부러 확인 안했어 일단 이 부분만 다시 확인해줘

2022-01-12 16:18 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/map/LocationListAdapter.kt
> +class LocationListAdapter : RecyclerView.Adapter<LocationListAdapter.LocationListViewHolder>() {
여기는 아이템들이 자주 바뀌는데 RecyclerView.Adapter 대신에 ListAdapter로 구현하는게 좀 더 좋지 않을까?

2022-01-12 16:18 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/map/LocationListAdapter.kt
> +    inner class LocationListViewHolder(
inner는 외부 클래스를 참조하기 때문에 메모리 릭의 위험성이 있어서 사용하지 않는 것을 권합니다. 그냥 중첩 클래스만으로 사용하는게 좋음

2022-01-12 16:18 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/map/MapSearchActivity.kt
> +        })
```suggestion
        binding.editSearch.doAfterTextChange {
            editTextBlankCheck()
        }
```
Androidx.core에 있는 함수를 활용하는 걸 권장합니다.

2022-01-12 16:18 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/map/MapSearchActivity.kt
> +        }
```suggestion
        binding.ivClear.isVisible = binding.editSearch.text.isNullOrEmpty()
```

이런 식으로 하면 [빈 공백으로만 이뤄진 문자열도 체크 가능](https://devbearkinf.tistory.com/46)합니다

2022-01-12 16:39 UTC, kkk5474096 commented on app/src/main/java/com/teamfillin/fillin/presentation/map/MapSearchActivity.kt
> +        }
저걸 왜 생각 못했지 감사합니다~

2022-01-12 16:40 UTC, kkk5474096 commented on app/src/main/java/com/teamfillin/fillin/presentation/map/MapSearchActivity.kt
> +        })
👍👍

2022-01-12 16:40 UTC, kkk5474096 commented on app/src/main/java/com/teamfillin/fillin/presentation/map/LocationListAdapter.kt
> +    inner class LocationListViewHolder(
참고하겠습니다~

2022-01-13 07:10 UTC, papajj06 approved these changes

2022-01-13 07:10 UTC, papajj06 commented on app/src/main/java/com/teamfillin/fillin/presentation/map/LocationListAdapter.kt
> +class LocationListAdapter :
LGTM~~~👍👍 good

2022-01-13 08:13 UTC, l2hyunwoo approved these changes
👍🏻

2022-01-13 08:14 UTC, merged