[feature/#20] 다이얼로그 구현
TeamFILL-IN/Fill-Android pull request #26
Opened 2022-01-14 07:48 UTC by papajj06

## Related Issues
close #20 

## What Did You Do?
- [x] 사진 상세보기 다이얼로그 구현

2022-01-14 08:30 UTC, kkk5474096 approved these changes
LGTM~👍

2022-01-14 08:49 UTC, l2hyunwoo requested changes
수고했어 리뷰 한번 보고 궁금한 거 있으면 질문 긔긔 👍🏻

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/HomeActivity.kt
> +class HomeActivity : AppCompatActivity() {
안쓰면 지우세요

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/HomeActivity.kt
> +
의미없는 빈줄은 가독성 저해요소입니다.

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/HomeActivity.kt
> +        )
지난번에도 말했다시피 이 부분은 변수 직접 참조보단 함수를 통해서 데이터를 전달하는게 더 안전합니다.

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/HomeActivity.kt
> +        newPhotosAdapter.notifyDataSetChanged()
이 부분 로직도 액티비티가 가져야하는 로직은 아닌 것 같습니다. 리사이클러뷰 자체의 로직이기 때문에 데이터가 변하는 곳에서 실행시키면 되는 로직인 것 같네요

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/HomeActivity.kt
> +        }
- 줄 정렬 안되어있습니다
- getVisibility, setVisibility는 java에서 사용하는 방식입니다. 코틀린에서는 visibility라는 프로퍼티를 통해서 접근할 수 있습니다.
- visibility를 활용하는 것보단 isVisible을 활용하여 boolean 값으로 visibility를 조절할 수 있습니다. 이걸 활용해보는 건 어떨까요?

```suggestion
                // core 모듈 내에 있는 기능 ㅎㅎ
                tvNotice.setOnClickListener {
                    toast("현상소 제보 Page이동")
                }
```

- apply는 블록안에 있는 사항들을 적용시킨 객체를 다른 변수에 대입할 때 사용하는 스코프 함수입니다. with(binding)이 이런 경우에서 일반적으로 사용됩니다.

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/NewPhotosAdapter.kt
> +        )
- 줄 정렬 요함

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/NewPhotosAdapter.kt
> +        }
```suggestion
    class NewPhotosViewHolder(
        private val binding: ItemNewPhotosListBinding
    ) : RecyclerView.ViewHolder(binding.root){
            fun onBind(data : NewPhotosData){
                Glide.with(binding.root)
                    .load(data.image)
                    .into(binding.ivNewPhoto)
            }
        }
```

일단 이런식으로 오른쪽으로 길어지는 코드는 안 만들 수 있음

또한 ImageView 같은 경우 ``binding.ivNewPhoto.load(data.image)``로도 작성할 수 있음(core 모듈 내에 ImageView 확장함수)

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/NewPhotosData.kt
> +    var image: Int
이건 Glide 사용할거니까 String으로 바꾸고 아무 image url 가져와서 사용하자

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/PhotoDialogFragment.kt
> +    private lateinit var button: ImageButton
굳이 View를 프래그먼트내에 상태변수로 가질 필요가 있을까?

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/PhotoDialogFragment.kt
> +        var view: View = inflater.inflate(R.layout.fragment_photo_dialog, container, false)
이미 binding으로 view에 접근할 수 있는데 이 view 변수는 어떤 역할을 하고 있는걸까? 중복된 변수이니 이건 활용하지 않는 것이 좋을 것 같음

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/PhotoDialogFragment.kt
> +        }
```suggestion
            binding.number.text = (
                binding.number.text.toString().toInt() +  (if (binding.heart.isSelected == false) 1 else -1)
            ).toString()
            binding.heart.isSelected = !binding.heart.isSelected
```

이런식으로 줄 줄이기 가능. 코드 이해 안가면 질문 ㄱ

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/PhotoDialogFragment.kt
> +        return _binding?.root
```suggestion
        return binding.root
```

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_home.xml
> +        android:layout_marginLeft="18dp"
```suggestion
        android:layout_marginStart="18dp"
```

안드로이드에서는 아랍권 국가까지 대응을 해가지고 왼쪽->오른쪽/오른쪽->왼쪽순으로 다르게 순서를 보여주게 할 수 있어. 이걸 자동으로 맞춰주기 위해서 Left/Right가 아니라 Start(읽기 시작하는 부분)/End(읽는 것이 끝나는 부분)으로 지정을 해. 이런 것까지 고려하면 위의 식으로 변경이 가능

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_home.xml
> +        app:layout_constraintLeft_toLeftOf="parent"
위 리뷰와 마찬가지

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_home.xml
> +        android:id="@+id/linear"
linear라고 하면 어떤것이 생각나니? 다른 사람이 봤을 때에도 대략적으로 연상이 가는 의미를 가진 id 네이밍이었으면 더 좋았을 것 같아

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_home.xml
> +            app:srcCompat="@drawable/ic_addphoto" />
👍🏻 근데 우리 minSdk가 26이어서 이것까지는 안해도 되기는 해 ㅎㅁㅎ

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_home.xml
> +        app:layout_constraintRight_toRightOf="parent"
```suggestion
        app:layout_constraintEnd_toEndOf="parent"
```

위와 동일 맥락

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_home.xml
> +        android:id="@+id/linear2"
> linear라고 하면 어떤것이 생각나니? 다른 사람이 봤을 때에도 대략적으로 연상이 가는 의미를 가진 id 네이밍이었으면 더 좋았을 것 같아

위와 마찬가지

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_home.xml
> +
줄 정렬 하시고

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_home.xml
> +    tools:ignore="MissingConstraints" />
이건 constraint를 제대로 안 갖춘 것 같은데 constrainTop 다시 맞춰야할 것 같아

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_home.xml
> +        android:backgroundTint="#dc4f1c"
color는 colors.xml에 정의된 것만 사용하자. 이거 안드로이드 과제 중 하나 아니었니ㅋㅋㅋㅋㅋ

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/res/layout/fragment_photo_dialog.xml
> +        android:id="@+id/ll_up"
> linear라고 하면 어떤것이 생각나니? 다른 사람이 봤을 때에도 대략적으로 연상이 가는 의미를 가진 id 네이밍이었으면 더 좋았을 것 같아

위와 마찬가지

2022-01-14 08:49 UTC, l2hyunwoo commented on app/src/main/res/layout/item_film_roll_pic.xml
> +        android:id="@+id/ll_up"
> linear라고 하면 어떤것이 생각나니? 다른 사람이 봤을 때에도 대략적으로 연상이 가는 의미를 가진 id 네이밍이었으면 더 좋았을 것 같아

위와 마찬가지

2022-01-14 08:52 UTC, papajj06 commented on app/src/main/java/com/teamfillin/fillin/PhotoDialogFragment.kt
> +        }
귯 오키요

2022-01-14 08:54 UTC, papajj06 commented on app/src/main/res/layout/activity_home.xml
> +        android:backgroundTint="#dc4f1c"
my 실수 오키용

2022-01-14 09:06 UTC, papajj06 commented on app/src/main/java/com/teamfillin/fillin/NewPhotosAdapter.kt
> +        }
좋네용

2022-01-15 02:24 UTC, l2hyunwoo requested changes
다시한번 봐주시기 바랍니다.

2022-01-15 02:24 UTC, l2hyunwoo commented on app/src/main/java/HomeMultiMode.kt
> +const val multi_type2 = 2
코틀린 코딩 컨벤션에서 상수는 UPPER_SNAKE_CASE로 적습니다

```suggestion
const val MULTI_TYPE_1 = 1
const val MULTI_TYPE_2 = 2
```

그리고 MULTI_TYPE_1은 어떤 의미를 가지고 있지 않은 것 같습니다. 어떤 용도로 만드신거죠?

2022-01-15 02:24 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/HomeActivity.kt
> +        val nextbutton = R.drawable.nextbutton
굳이 변수로 선언하신 이유가 있을까요? 그냥 패러미터에 바로 꽂아넣어도 될 것 같네요

2022-01-15 02:24 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/HomeActivity.kt
> +    @SuppressLint("WrongConstant")
이 SuppressLint가 발생한 이유가 있을건데 다시 한번 코드 수정 부탁드립니다. 그리고 LinearLayoutManager 같은 경우 코드에서 만드시는 것보다 xml에서 app:layoutManager로 설정하시는게 더 좋습니다.

2022-01-15 02:24 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/HomeActivity.kt
> +                    clPopup.isVisible = false
```suggestion
              clPopup.isVisible = !clPopup.isVisible
```

이렇게 바꿀 수 있지 않을까요?

2022-01-15 02:24 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/NewPhotosAdapter.kt
> +    inner class MultiViewHolder1(private val binding: ItemNewPhotosListBinding) :
inner class는 외부 클래스를 참조하기때문에 메모리 릭을 발생시킬 수 있습니다. 좋은 패턴이 아니기에 class로 바꾸시기를 권장합니다. 또한 이름도 어떤것을 의미하는지 잘 모르겠습니다. **클래스와 변수명은 그 용도에 맞춰서 작성해주시기 바랍니다**

2022-01-15 02:24 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/PhotoDialogFragment.kt
> +            binding.heart.isSelected = !binding.heart.isSelected
이거 혹시 에뮬레이터 돌려서 테스트 해보셨나요?

2022-01-15 02:24 UTC, l2hyunwoo commented on app/src/main/AndroidManifest.xml
> +            </intent-filter>
이렇게 설정하면 앱 실행은 되던가요?

2022-01-15 02:26 UTC, papajj06 commented on app/src/main/java/com/teamfillin/fillin/PhotoDialogFragment.kt
> +            binding.heart.isSelected = !binding.heart.isSelected
넹 됩니댜ㅏ

2022-01-15 02:27 UTC, papajj06 commented on app/src/main/AndroidManifest.xml
> +            </intent-filter>
그부분 실쑤,,,고쳤습당

2022-01-15 03:26 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/HomeActivity.kt
> +                var dialog = PhotoDialogFragment()
이거 값 변경 안할거면 var -> val 로 바꾸세요

2022-01-16 02:39 UTC, l2hyunwoo approved these changes
가독성이 많이 좋아졌군요! 훌륭합니다 아래 부분만 보고 머지 가보자고!

2022-01-16 02:39 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/home/NewPhotosAdapter.kt
> +                (holder as NewPhotosViewHolder).bind(photolist[position])
이 부분을 추상화하는건 다음에 배워보도록 합시다! 하지만 지금 상태도 가독성이 좋아

2022-01-16 02:39 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/home/NewPhotosAdapter.kt
> +    inner class NewPhotosViewHolder(private val binding: ItemNewPhotosListBinding) :
inner...제거해달라구...!!

2022-01-16 02:39 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/dialog/PhotoDialogFragment.kt
> +
빈줄삭제 plz

2022-01-16 02:39 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/home/HomeActivity.kt
> +        setContentView(binding.root)
BindingActivity에서는 이거 할 필요 없습당 ㅎㅁㅎ

2022-01-16 02:39 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/home/NewPhotosAdapter.kt
> +                (holder as NewPhotosViewHolder).bind(photolist[position])
(이건 넘어가도 된다는 리뷰라는 뜻)

2022-01-16 02:40 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/home/HomeActivity.kt
> +        setContentView(binding.root)
이거 -> setContentView() 지우쎄영

2022-01-16 05:38 UTC, merged