[feature/#19] 사진업로드 뷰 구현
TeamFILL-IN/Fill-Android pull request #28
Opened 2022-01-16 06:39 UTC by hyunji24

## Related Issues
close #19 

## What Did You Do?
- [x] 상단바
- [x] Film/Studio 입력
- [x] Add 버튼

2022-01-16 06:53 UTC, l2hyunwoo requested changes
한번 리뷰 보실

2022-01-16 06:53 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/CustomAddCompleteDialog.kt
> +    }
```suggestion
    fun interface OnDialogClickListener{
        fun onClicked()
    }
```

코틀린에서 함수가 한 개인 인터페이스는 함수형 interface(fun interface)로 설계가 가능합니다. 이걸 사용하면 사용부에서 object : OnDialogClickListener 이런 구현코드를 지울 수 있음!

2022-01-16 06:53 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/CustomAddCancelDialog.kt
> +    }
```suggestion
    fun interface OnDialogClickListener{
        fun onClicked()
    }
```

이것두~

2022-01-16 06:53 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/AddPhotoActivity.kt
> +            })
```suggestion
            addCancelDialog.setOnClickListener(CustomAddCancelDialog.OnDialogClickListener {
                // 이런식으로 작성 가능!
            })
```

아래와 같이 fun interface로 바꾸면 이렇게 바꾸라고 뜰거임!

2022-01-16 06:53 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_add_photo.xml
> +        <androidx.appcompat.widget.Toolbar xmlns:tools="http://schemas.android.com/tools"
우리는 Material Design Component 기준으로 작성하기 때문에 Toolbar로 고치는걸 권장
```suggestion
        <Toolbar xmlns:tools="http://schemas.android.com/tools"
```

2022-01-16 16:56 UTC, hyunji24 commented on app/src/main/java/com/teamfillin/fillin/presentation/CustomAddCompleteDialog.kt
> +    }
아하 좋은거 배워갑니다잉,,🙂

2022-01-16 16:57 UTC, hyunji24 commented on app/src/main/res/layout/activity_add_photo.xml
> +        <androidx.appcompat.widget.Toolbar xmlns:tools="http://schemas.android.com/tools"
오케이!

2022-01-16 16:57 UTC, hyunji24 commented
> 한번 리뷰 보실

교수님 최고최고👍

2022-01-17 06:06 UTC, l2hyunwoo approved these changes
좋아! 아래 내용만 확인하고 머지가자

2022-01-17 06:06 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/AddPhotoActivity.kt
> +            }
굳!

2022-01-17 06:06 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/CustomAddCompleteDialog.kt
> +class CustomAddCompleteDialog(context: Context) {
굳이 앞에 Custom 안 붙여도 될 것 같아. 예를 들어서 우리가 애들이랑 엽떡먹으러 갈때 그냥 엽떡 먹으러간다고 하지 "캡사이신 소스에 떡, 소시지, 모짜렐라 치즈를 버무린 엽기 떡볶이 먹으러가자"고 하진 않잖아. 과다한 정보는 오히려 정보가 주려고 하는 의미를 해칠 수 있어요

2022-01-17 06:06 UTC, l2hyunwoo commented on app/src/main/res/layout/dialog_addphoto_cancel.xml
> +    <androidx.appcompat.widget.AppCompatButton
이것도 위의 Toolbar와 마찬가지긴 한데 머티리얼 버튼이 좀 다루기 어려운 감이 있긴해서 이대로 가도 괜찮을 것 같아요

2022-01-17 06:07 UTC, l2hyunwoo commented
어머나 컨플릭도 있네 화이팅!

2022-01-17 12:21 UTC, hyunji24 commented on app/src/main/java/com/teamfillin/fillin/presentation/CustomAddCompleteDialog.kt
> +class CustomAddCompleteDialog(context: Context) {
엽떡비유 최고시다  '캡사이신 소스에 떡 버무린' 없애러 갑니다

2022-01-17 12:23 UTC, papajj06 commented on app/src/main/java/com/teamfillin/fillin/presentation/CustomAddCompleteDialog.kt
> +class CustomAddCompleteDialog(context: Context) {
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ누누 찰떢 비유 좋숩니다

2022-01-17 12:25 UTC, papajj06 approved these changes

2022-01-17 12:25 UTC, papajj06 commented on app/src/main/java/com/teamfillin/fillin/presentation/AddPhotoActivity.kt
> +            }
LGTM~~👍👍

2022-01-17 14:23 UTC, l2hyunwoo requested changes
권한 설정만 변경해주세요

2022-01-17 14:38 UTC, l2hyunwoo approved these changes
머지 고

2022-01-17 15:18 UTC, merged