[Feature/#27] 필름롤 , 카테고리 뷰 구현
TeamFILL-IN/Fill-Android pull request #30
Opened 2022-01-17 07:57 UTC by papajj06

## Related Issues
필름롤 메인 뷰, 카테고리 뷰

## What Did You Do?
- [x] 메인 뷰 구현
- [x] 카테고리 뷰 구현
- [x] adapter 생성

2022-01-17 10:45 UTC, l2hyunwoo requested changes
수고하셨습니당

2022-01-17 10:45 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/category/FilmCategoryAdapter.kt
> +        }
굳!

2022-01-17 10:45 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/category/FilmCategoryAdapter.kt
> +    }
```suggestion
    fun interface OnItemClickListener {
        fun onClick(v: View, position: Int)
    }
```

[이렇게도 만들 수](https://github.com/TeamFILL-IN/Fill-Android/pull/28#discussion_r785397902) 있습니당!

2022-01-17 10:45 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/category/FilmCategoryAdapter.kt
> +    private lateinit var itemClickListener: OnItemClickListener
private 선언 굳

2022-01-17 10:45 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/category/FilmCategoryAdapter.kt
> +        }
core 패키지에 ItemDiffCallback 있으니 이걸 활용하면

```kotlin
class FilmCategoryAdapter :
    ListAdapter<CategoryInfo, FilmCategoryAdapter.FilmListViewHolder>(
        ItemDiffCallback(
            onItemsTheSame = { old, new -> old.film== new.film },
            onContentsTheSame = { old, new -> old == new }
        )
    )
```

이런식으로도 적을 수 있음!

2022-01-17 10:45 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/data/CategoryInfo.kt
> +
```suggestion
data class CategoryInfo(
    val film: String
) 

fun String.toCategoryInfo() = CategoryInfo(this)
```

여기에 이 함수를 추가하면?

2022-01-17 10:45 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/category/FilmRollCategoryActivity.kt
> +            )
```suggestion
    List(6) { "Kodak color plus 200 abcdefg1234567".to toCategoryInfo() }
```

이렇게 적을 수 있습니당!

2022-01-17 10:45 UTC, l2hyunwoo commented on build.gradle.kts
> +        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10")
이거 바꿔주세용

2022-01-17 12:01 UTC, papajj06 commented on app/src/main/java/com/teamfillin/fillin/presentation/category/FilmRollCategoryActivity.kt
> +            )
실화여~~??? 짱좋숩니댜,,ㅎㅎ 최고최고 👍👍👍

2022-01-17 14:50 UTC, kkk5474096 reviewed
쵝오다~

2022-01-17 14:50 UTC, kkk5474096 commented on app/src/main/java/com/teamfillin/fillin/presentation/category/FilmRollCategoryActivity.kt
> +    }
내 코드에선 toolbar에서 뒤로가기 버튼을 이미지로 만드는게 아니라 안드로이드 자체에서 구현해주는 코드로 써서 이 코드가 필요해
너는 이미지로 뒤로가기 버튼을 넣었기 때문에 필요가 없는 코드입니다

2022-01-17 14:50 UTC, kkk5474096 commented on app/src/main/res/layout/activity_film_roll.xml
> +        app:layout_constraintStart_toStartOf="parent"
android:layout_width="match_parent"
match 일때는 start랑 end 제약 안해줘도 됩니다

2022-01-19 09:11 UTC, l2hyunwoo approved these changes
수고하셨습니다

2022-01-19 09:11 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/filmroll/CurationAdapter.kt
> +            binding.tvCuration.text = "따뜻한 사진을 \n 원한다면"
```suggestion
            binding.tvCuration.text = "따뜻한 사진을\n원한다면"
```

이렇게 나오면

```
따뜻한 사진을
 원한다면
```

이런식으로 텍스트가 보여지겠쥬?

2022-01-19 09:11 UTC, l2hyunwoo commented on app/src/main/AndroidManifest.xml
> +            android:exported="true" />
exported="false"로 바꿔주세용

2022-01-19 09:11 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/data/CategoryInfo.kt
> +)
이거 안쓰면 지워주세용

2022-01-19 09:11 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/home/HomeActivity.kt
> +
빈줄 지워주시고

2022-01-19 09:30 UTC, merged

2022-01-19 09:32 UTC, papajj06 commented on app/src/main/AndroidManifest.xml
> +            android:exported="true" />
넵넵 ~!~!