[Feature/#27] 필름롤 , 카테고리 뷰 코드리뷰 수정
TeamFILL-IN/Fill-Android pull request #46
Opened 2022-01-19 13:17 UTC by papajj06

## Related Issues
코드리뷰 수정 및 develop , Home 서버 브랜치 pull 받음

## What Did You Do?
- [x] 코드리뷰 반영 수정

2022-01-20 07:43 UTC, l2hyunwoo requested changes
디벨롭 푸시 하지마 ^^

2022-01-20 12:21 UTC, l2hyunwoo reviewed
이거 테스트한거 화면 사진찍어서 올려줘

2022-01-20 12:21 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/home/HomeActivity.kt
> +            Timber.d("Error")
```suggestion
            Timber.e(it)
```

이런식으로 에러 로깅하는게 좋음

2022-01-20 12:21 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/home/HomeActivity.kt
> +            Timber.d("데이터 넘어오나?", "${userData?.user?.nickname}")
데이터 로깅 넘어오는거 확인했으면 삭제하세요

2022-01-20 12:21 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/filmroll/FilmRollActivity.kt
> +                Timber.d("Error $it")
```suggestion
                Timber.e(it)
```

2022-01-20 12:21 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/filmroll/CurationAdapter.kt
> +    ListAdapter<ResponseFilmRoll.Curation, RecyclerView.ViewHolder>(CurationDiffUtil()) {
이렇게 하면 리스트 나옴? FilmPhotoInfo가 들어와야 사진 리스트가 보여지지 않나?

2022-01-20 12:21 UTC, l2hyunwoo commented on app/src/main/java/com/teamfillin/fillin/presentation/filmroll/CurationAdapter.kt
> +        fun bind(film: ResponseFilmRoll.Curation) {
이것도 마찬가지...photoList 내가 기억하는 걸로 "5, 6, 7," 막 이런거 들어오는걸로 알고 있는데

2022-01-21 06:58 UTC, l2hyunwoo approved these changes
어프루브 갈격!!!!!!!

2022-01-21 06:59 UTC, kkk5474096 approved these changes
LGTM~

2022-01-21 08:17 UTC, merged